### ISSUE TITLE
Question: how to generate .yaml file from pytest test(s)

### ISSUE THREAD

**Issue by UANEMESIS** [mharrisb1/openai-responses-python#57]
Greetings!
I have a question. Trying to find how to generate .yaml file from pytest (api) tests.
I need this file for OpenAPI Definition (to generate some API doc).

**Comment by mharrisb1** [comment]
I'm a little confused on the ask here. A YAML file of what?

**Comment by UANEMESIS** [comment]
@mharrisb1 probably I didn't understand correctly purpose of this library.
I thought that using this lib we can generate JSON or YAML file from pytest API tests. For example, we doing API request using requests library and according to request + response can be generated JSON/YAML file, like we have it in Postman (export collection functionality).

**Comment by mharrisb1** [comment]
No sorry. This is for [OpenAI](https://openai.com) API testing

**Comment by UANEMESIS** [comment]
@mharrisb1 and sorry from me to you! 🤝
