### ISSUE TITLE
Using AzureOpenAI client doesn't correctly mock endpoints

### ISSUE THREAD

**Issue by alastairs** [mharrisb1/openai-responses-python#66]
Hi there, I picked up [the Azure client example](https://github.com/mharrisb1/openai-responses-python/blob/main/examples/test_azure_client.py) linked in #9 and noted the following line in the test failure output:

```plain
E                   respx.models.AllMockedAssertionError: RESPX:
<Request('POST',
'https://example-endpoint.openai.azure.com/openai/deployments/gpt-4o-monitoring/chat/completions?api-version=2024-02-01')>
not mocked!
```

Here's a repro, slightly adapting your example to fit what I'm trying to do:

```python
def create_AzureOpenAI_completion(client: AzureOpenAI):
    return client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Hello!"},
        ]
    )

@openai_responses.mock()
def test_mock_client(openai_mock):
    client = AzureOpenAI(
        azure_endpoint="https://example-endpoint.openai.azure.com",
        api_key="fakeKey123",
        api_version="2024-02-01"
    )

    completion = create_AzureOpenAI_completion(client)

    assert len(completion.choices) == 1
    assert completion.choices[0].message.content == "Hello! How can I help?"
    assert openai_mock.chat.completions.create.route.call_count == 1
```

In this case `create_AzureOpenAI_completion` is an analog for my system under test which makes the actual calls on the `AzureOpenAI` client for which I want to create some canned responses. 

Package versions:
```requirements.txt
openai==1.51.2
openai-responses==v0.11.1
```

**Comment by alastairs** [comment]
Apologies, closer inspection revealed I'd missed out specifying the `base_url` argument for the decorator.

**Comment by mharrisb1** [comment]
@alastairs no problem. Glad you got it figured out. I definitely need to add a more explicit note on this in the docs when I find the time
