### ISSUE TITLE
Add support for OpenAI 1.55

### ISSUE THREAD

**Issue by Nardol** [mharrisb1/openai-responses-python#67]
OpenAI 1.55 fix an issue with latest version of httpx.
Could it be possible to also support this version and publish a new release?

**Comment by mharrisb1** [comment]
Thanks for creating the issue. Looks like [RESPX](https://github.com/lundberg/respx) needs to also be updated to support [HTTX 0.28](https://github.com/encode/httpx/releases/tag/0.28.0). Looking for this PR to be merged https://github.com/lundberg/respx/pull/278

**Comment by mharrisb1** [comment]
In the meantime, I've added a release candidate for this fix that you can use instead of pulling from PyPi.

```sh
# poetry
poetry add git+https://github.com/mharrisb1/openai-responses-python#v0.11.3-rc1

# pip
pip install git+https://github.com/mharrisb1/openai-responses-python#v0.11.3-rc1
```

**Comment by mharrisb1** [comment]
#68 fully closes this issue.

Release `0.11.3` now available in PyPI
