### ISSUE TITLE
feat: base url override

### ISSUE THREAD

**Issue by mharrisb1** [mharrisb1/openai-responses-python#9]
Allow Azure and other custom URLs in place of OpenAI URLs

**Comment by mapohjola** [comment]
This actually does not work because all the routes add `/v1/` which is not present in Azure client

**Comment by mharrisb1** [comment]
Thanks @mapohjola will take a look at this

**Comment by mharrisb1** [comment]
@mapohjola would moving `/v1` version prefix to the default base URL solve it for you? Taking a look at the Azure URLs this should work but maybe you're using something else.

**Comment by mapohjola** [comment]
> @mapohjola would moving `/v1` version prefix to the default base URL solve it for you? Taking a look at the Azure URLs this should work but maybe you're using something else.

Yes that would solve the issue for Azure

**Comment by mharrisb1** [comment]
Just released a fix for this. Upgrading to [v0.3.4](https://pypi.org/project/openai-responses) should resolve

**Comment by mharrisb1** [comment]
Feel free to reopen if this doesn't work. I added an example for using Azure client [here](https://github.com/mharrisb1/openai-responses-python/blob/main/examples/test_azure_client.py) but I didn't do much more than that to ensure it worked.
